promptList = [
    { "name": "Minimalist", "description": "Clean, simple, with a lot of white space." },
    { "name": "Retro", "description": "Inspired by a specific era, like the '60s, '70s, '80s." },
    { "name": "Bohemian", "description": "Free-spirited, eclectic, with earthy tones." },
    { "name": "Industrial", "description": "Raw, unfinished look with metals, woods, and exposed brick." },
    { "name": "Vintage", "description": "Old-fashioned, nostalgic, often with muted colors." },
    { "name": "Futuristic", "description": "Sleek, techy, often with neon or metallic elements." },
    { "name": "Rustic", "description": "Earthy, natural, often with wood and stone elements." },
    { "name": "Elegant", "description": "Sophisticated, often with muted colors and cursive fonts." },
    { "name": "Whimsical", "description": "Playful, dreamy, and fun." },
    { "name": "Grunge", "description": "Dark, gritty, and edgy." },
    { "name": "Art Deco", "description": "Inspired by the 1920s and 1930s, with bold geometric shapes." },
    { "name": "Flat", "description": "No shadows, simple elements, and bright colors." },
    { "name": "Material Design", "description": "Inspired by Google's design language, with depth effects." },
    { "name": "Neumorphism", "description": "Soft UI, with subtle shadows, highlights, and semi-flat colors." },
    { "name": "Dark Mode", "description": "Dark backgrounds with light text, popular for reducing eye strain." },
    { "name": "Parallax", "description": "Background images move slower than foreground images, creating depth." },
    { "name": "Hand-drawn", "description": "Elements look like they've been sketched or doodled." },
    { "name": "Watercolor", "description": "Soft, blended colors that mimic a watercolor painting." },
    { "name": "Photographic", "description": "Large, high-quality photos as the main design element." },
    { "name": "Collage", "description": "Mix of photos, illustrations, and text, often with a cut-out feel." },
    { "name": "Typography-focused", "description": "Design centered around unique and bold typography." },
    { "name": "Monochromatic", "description": "Using different shades of a single color." },
    { "name": "Neon", "description": "Bright, fluorescent colors, often with a cyberpunk or '80s vibe." },
    { "name": "Nature-inspired", "description": "Using natural colors, patterns, and images." },
    { "name": "Abstract", "description": "Non-representational shapes and patterns." },
    { "name": "Mosaic", "description": "Made up of small pieces or tiles to create a larger image." },
    { "name": "Magazine-style", "description": "Layouts that mimic the look of print magazines." },
    { "name": "Gothic", "description": "Dark, mysterious, often with ornate elements." },
    { "name": "Beachy", "description": "Light, airy, with pastel colors and beach-related imagery." },
    { "name": "Urban", "description": "Inspired by city life, with grays, blacks, and metallics." },
    { "name": "Steampunk", "description": "Victorian-era aesthetics combined with steam-powered technology." },
    { "name": "Cyberpunk", "description": "Futuristic, neon-lit urban landscapes with high-tech themes." },
    { "name": "Zen", "description": "Calm, balanced, inspired by Japanese simplicity." },
    { "name": "Nautical", "description": "Marine-themed, with blues, whites, and oceanic elements." },
    { "name": "Space", "description": "Galaxies, stars, and other outer space elements." },
    { "name": "Desert", "description": "Warm tones, cacti, and sunsets." },
    { "name": "Tropical", "description": "Bright colors, palm trees, and beach vibes." },
    { "name": "Artsy", "description": "Creative, colorful, with paint strokes and splashes." },
    { "name": "Geometric", "description": "Focused on shapes, lines, and patterns." },
    { "name": "Classic", "description": "Timeless design with traditional elements." },
    { "name": "Romantic", "description": "Soft colors, florals, and delicate typography." },
    { "name": "Sporty", "description": "Dynamic, bold, inspired by various sports." },
    { "name": "Adventure", "description": "Mountains, forests, and elements for the wanderlust." },
    { "name": "Cinematic", "description": "Movie-inspired, with film reels, clapperboards, and more." },
    { "name": "Sci-Fi", "description": "Inspired by science fiction, with futuristic tech and alien motifs." },
    { "name": "Fantasy", "description": "Dragons, castles, and other magical elements." },
    { "name": "Horror", "description": "Dark, eerie, with motifs like bats, ghosts, and haunted houses." },
    { "name": "Western", "description": "Cowboys, deserts, and saloon-inspired designs." },
    { "name": "Jungle", "description": "Lush greenery, animals, and tropical vibes." },
    { "name": "Arctic", "description": "Cool tones, icebergs, and polar animals." },
    { "name": "Mystical", "description": "Mystic symbols, crystals, and ethereal vibes." },
    { "name": "Gamer", "description": "Inspired by video games, pixels, and controllers." },
    { "name": "Pop Art", "description": "Bold colors, comic strips, and 1950s aesthetics." },
    { "name": "Origami", "description": "Paper-folded designs and geometric patterns." },
    { "name": "Craft", "description": "Handmade feel, with textures like paper, fabric, and yarn." },
    { "name": "Gourmet", "description": "Food-inspired, with utensils, plates, and ingredients." },
    { "name": "Music", "description": "Notes, instruments, and other musical elements." },
    { "name": "Travel", "description": "Landmarks, maps, and globetrotting vibes." },
    { "name": "Tech", "description": "Digital, circuitry, and modern technology elements." },
    { "name": "Eco-friendly", "description": "Green, sustainable, with nature and recycling motifs." },
    { "name": "Childlike", "description": "Bright colors, simple shapes, and playful vibes." },
    { "name": "Historical", "description": "Inspired by different historical periods and artifacts." },
    { "name": "Luxury", "description": "Gold, diamonds, and a touch of opulence." },
    { "name": "Fairy Tale", "description": "Castles, fairies, and storybook themes." },
    { "name": "Military", "description": "Camo patterns, badges, and army-inspired designs." },
    { "name": "Urban Jungle", "description": "Combination of city elements with lush greenery." },
    { "name": "Digital Native", "description": "Pixel art, early web aesthetics, and tech nostalgia." },
    { "name": "Farmhouse", "description": "Rural, cozy, with barns and farm animals." },
    { "name": "Mediterranean", "description": "Sea blues, terracotta, and sun-soaked vibes." },
    { "name": "Safari", "description": "African landscapes, animals, and tribal patterns." },
    { "name": "Carnival", "description": "Bright colors, tents, and circus elements." },
    { "name": "Underwater", "description": "Marine life, bubbles, and deep-sea aesthetics." },
    { "name": "Sky", "description": "Clouds, birds, and airy designs." },
    { "name": "Street Art", "description": "Graffiti, murals, and urban art vibes." },
    { "name": "Bauhaus", "description": "Geometric shapes and a blend of art, craft, and technology." },
    { "name": "Academic", "description": "Books, glasses, and school-inspired designs." },
    { "name": "Garden", "description": "Flowers, plants, and a touch of nature." },
    { "name": "Nightlife", "description": "Neon lights, cocktails, and urban night vibes." },
    { "name": "Rainforest", "description": "Dense vegetation, wildlife, and tropical rain." },
    { "name": "Mountain", "description": "Peaks, snow, and high-altitude vibes." },
    { "name": "Prairie", "description": "Open fields, wildflowers, and serene landscapes." },
    { "name": "Island", "description": "Palm trees, sand, and isolated paradise vibes." },
    { "name": "Galactic", "description": "Beyond our galaxy, with stars, black holes, and more." },
    { "name": "Dystopian", "description": "Post-apocalyptic, with ruins and a sense of decay." },
    { "name": "Utopian", "description": "Idealistic, harmonious, and perfect-world designs." },
    { "name": "Martial Arts", "description": "Dojos, symbols, and combat-inspired elements." },
    { "name": "Pirate", "description": "Skulls, ships, and treasure hunt vibes." },
    { "name": "Cottagecore", "description": "Rural life, simplicity, and nostalgic countryside vibes." },
    { "name": "Cityscape", "description": "Skylines, tall buildings, and urban views." },
    { "name": "Forest", "description": "Trees, wildlife, and deep woods vibes." },
    { "name": "Desert Oasis", "description": "Sand dunes combined with refreshing water elements." },
    { "name": "Harbor", "description": "Docks, ships, and a maritime feel." },
    { "name": "Mystic Forest", "description": "Enchanted woods, magical creatures, and fairy vibes." },
    { "name": "Celestial", "description": "Moon, stars, and cosmic designs." },
    { "name": "Glacier", "description": "Icy landscapes, cool tones, and arctic vibes." },
    { "name": "Sunset", "description": "Warm hues, horizons, and evening serenity." },
    { "name": "Dawn", "description": "Soft light, pastels, and the promise of a new day." },
    { "name": "Festival", "description": "Music, lights, and celebratory vibes." },
    { "name": "Meadow", "description": "Open fields, butterflies, and sunny day vibes." },
    { "name": "Lunar", "description": "Moon phases, night skies, and celestial mystery." },
    { "name": "Solar", "description": "Sun motifs, warmth, and radiant energy." },
    { "name": "Digital Realm", "description": "Virtual reality, digital landscapes, and cyber vibes." },
    { "name": "Harvest", "description": "Autumn colors, crops, and a sense of abundance." },
    { "name": "Winter Wonderland", "description": "Snowflakes, icy motifs, and chilly vibes." },
    { "name": "Spring Bloom", "description": "Flowers, fresh starts, and rejuvenation." },
    { "name": "Summer Breeze", "description": "Beach vibes, sun hats, and relaxation." }
]



// Create and export a variable called tags that is a list of strings of the general themes of this component (i.e. the kinds of styles being represented by it). These should be human readable concepts related to the visual styles of the component.